### ISSUE TITLE
Update near-api-js when https://github.com/near/near-api-js/pull/620 is released

### ISSUE THREAD

**Issue by paouvrard** [aurora-is-near/rainbow-bridge-client#46]
This PR https://github.com/aurora-is-near/rainbow-bridge-client/pull/45 installed near-api-js from commit to handle borsh in viewMethods

**Comment by raymondfeng** [comment]
@paouvrard Can we update to the latest release of `near-api-js`? This module assumes singleton ethProvider/nearConnection and it's hard to use different versions of `near-api-js` in the dependency tree.

**Comment by paouvrard** [comment]
@raymondfeng This PR https://github.com/near/near-api-js/pull/620 doesn't appear to have been release in near-api-js.
cc @mfornet

**Comment by paouvrard** [comment]
Resolved.
