### ISSUE TITLE
Increase gas attached to `deploy_bridge_token`

### ISSUE THREAD

**Issue by jakmeier** [aurora-is-near/rainbow-bridge-client#76]
Deployment costs per byte of code are going to be increased by a factor of ~5 with this change to NEAR protocol: https://github.com/near/nearcore/pull/6397

Probably this will be included with protocol version 53, which would be released on testnet by March 23 and on mainnet by April 20.

To find everyone affected by this change, I listed all the indirect deployments from the past that would fail with the new cost, if all gas attachments stay the same. `factory.bridge.near` appeared as signer 112 times in that list. I didn't go through all of them but I think it's always due to`deploy_bridge_token` only having 60Tgas attached. ([Example](https://explorer.near.org/transactions/8EAwQmq4SqqBDvAhVyj9zrzRn5MuzHgyBxaT7bTdfNP5#2rnjvWsxLNZj4j1QLBUfekGFu5eDJY8KnrUW8itYYDKk))

A contract with 222kB (current size of [bridge_token.wasm](https://github.com/aurora-is-near/rainbow-token-connector/blob/e3ac72522cb0d51c3f03bc75e66cc70a6245c49b/res/bridge_token.wasm)) will see its gas cost increased by about 13Tgas.

Your current gas limit of 60Tgas, defined in [deploy.ts](https://github.com/aurora-is-near/rainbow-bridge-client/blob/21ef48e78edc3a76085ed14a60091ce2e010dcf8/packages/nep141-erc20/src/bridged-nep141/deploy.ts), is *probably* just about okay with that. But if you want to be on the safe side, I would increase it. Extra gas is fully refunded anyway.

**Comment by paouvrard** [comment]
@jakmeier Thank you for the warning! Did a new `deploy_bridge_token` tx with same gas settings on testnet v53 doesn't appear to be any issue: https://explorer.testnet.near.org/transactions/AK2mQaLrhkpbkWtaJEPhE68jKJ71w8BGmtFqCCGe42Sd

**Comment by jakmeier** [comment]
Yes, looks good. Thanks for the update!
