### ISSUE TITLE
 BorshError: Expected buffer length 20 isn't within bounds: recipient

### ISSUE THREAD

**Issue by dlpigpen** [aurora-is-near/rainbow-bridge-client#77]
It comes from the line code in the file src/rainbown/nep141-erc20/src/bridged-nep141/sendToEthereum/index.ts:334:41)
```
  const withdrawEvent = deserializeBorsh(
    SCHEMA, WithdrawEvent, Buffer.from(successValue, 'base64')
  ) as { amount: BN, token: Uint8Array, recipient: Uint8Array}
```

**Comment by dlpigpen** [comment]
The same issue in the file ethXnear.naturalNEAR.recover BorshError: Unexpected 19 bytes after deserialized data

```
ethXnear.naturalNEAR.recover BorshError: Unexpected 19 bytes after deserialized data
    at deserialize (/node_modules/borsh/lib/index.js:405:15)
    at Object.recover (/src/rainbown/near-ether/src/natural-near/sendToEthereum/index.ts:315:37)
    ```

**Comment by paouvrard** [comment]
It appears your NEAR transaction which started the transfer doesn't contain the recipient on Ethereum. Do you have the NEAR testnet transaction to reproduce ?

**Comment by dlpigpen** [comment]
> you can reproduce with txHash 'H6oYtGjZPtV2S74s32Nswrckah4eLGyeNB6u74X9sLnw'

**Comment by paouvrard** [comment]
The hash provided in an ETH transfer, so you should be using `@near-eth/near-ether/bridged-ether/sendToEthereum`.
https://testnet.rainbowbridge.app/transfer/H6oYtGjZPtV2S74s32Nswrckah4eLGyeNB6u74X9sLnw

**Comment by dlpigpen** [comment]
I think it made by a mistake. any way how to recover a tx hash without knowing type if transfer?

**Comment by paouvrard** [comment]
You could query the tx information to see which contract is being called, or just try/catch `recover` from the different packages.
